spring:
  application:
    name: spotter
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    livereload:
      enabled: false
server:
  port: 8080

fusionAuth:
  url: http://localhost:9011
  apiKey: ${FUSIONAUTH_API_KEY}
  applicationId: ${FUSIONAUTH_CLIENT_ID}